language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

jobs:
  allow_failures:
    - rust: nightly
  include:
    - 
    - language: node_js
      node_js: "12"
      script:
      - yarn ava
      
      cache: yarn