[package]
name = "lavender_gb"
version = "0.0.1"
authors = ["McKayla Washburn <mckayla@hey.com>"]
description = "Decoder and disassembler for LR35902 instructions"
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "./lib.rs"

[dependencies]
num_enum = { workspace = true }
