[book]
title = "The Ultimate Game Boy Advance Reference"
author = "McKayla Washburn <mckayla@hey.com>"
description = "Detailed examples of how to build a Game Boy Advance emulator, with source code and examples."
language = "en-US"
