name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-js:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x]
            fail-fast: false

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - run: node -v
            - run: yarn -v
            - run: cargo -V

            - run: yarn

            - run: yarn prettier --ignore-path .gitignore --check .

            - run: yarn workspace @lavender/core build

            - run: yarn workspace lavender lint
            - run: yarn workspace lavender type-check
            - run: yarn workspace lavender test
            - run: yarn workspace lavender build

    build-rs:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                rust-version: [stable, beta, nightly]
            fail-fast: false

        steps:
            - uses: actions/checkout@v2

            - run: rustup default ${{ matrix.rust-version }}

            - run: rustc -V
            - run: cargo -V

            - run: rustup component add rustfmt
              if: matrix.rust-version == 'stable'
            - run: rustup component add clippy
              if: matrix.rust-version == 'stable'

            - run: cargo fmt -- --check
              if: matrix.rust-version == 'stable'
            - run: cargo clippy
              if: matrix.rust-version == 'stable'

            - run: cargo build --verbose
            - run: cargo test --verbose
